version: '3.4'

services:
  ponyracer:
    image: ponyracer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "9229:9229"
      - "4200:4200"
    volumes:
      - .:/usr/app
